import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Script
          src="https://kit.fontawesome.com/c2a7616b54.js"
          strategy="lazyOnload"
          crossOrigin="anonymous"
        />
        {/* <Script
          src="https://s3.amazonaws.com/idme/developer/idme-buttons/assets/js/idme-wallet-button.js"
          strategy="lazyOnload"
        />{" "} */}
      </body>
    </html>
  );
}
